(function(){
"use strict";
var EW=2550,EH=3300,PW=765,PH=990,currentType="welcome",editingPage=null;
var modules=[["▦","MBG — Labirynty","mbg.html?view=mbg#workflow-maze"],["◫","Complete the Picture","modules/complete-picture/complete-picture.html"],["✦","Coloring Studio","modules/coloring-studio/coloring-studio.html"],["〰","Tracing Studio","modules/tracing-studio/tracing-studio.html"],["⇄","Matching Studio","modules/matching-studio/matching-studio.html"],["Aa","Alphabet Studio","modules/alphabet-studio/alphabet-studio.html"],["∑","Math Studio","modules/math-studio/math-studio.html"],["•••","Dot to Dot Studio","modules/dot-to-dot-studio/dot-to-dot-studio.html"],["◎","Hidden Objects Studio","modules/hidden-objects-studio/hidden-objects-studio.html"],["◇","Logic Studio","modules/logic-studio/logic-studio.html"],["🔤","Word Search Studio","modules/word-search-studio/word-search-studio.html"]];
function $(id){return document.getElementById(id)}function val(id,f){var n=$(id);return n?String(n.value||""):f}function num(id,f){var n=Number(val(id,f));return Number.isFinite(n)?n:f}function clamp(v,a,b){return Math.min(b,Math.max(a,v))}function id(){return window.crypto&&crypto.randomUUID?crypto.randomUUID():"bb-"+Date.now().toString(36)+"-"+Math.random().toString(36).slice(2,8)}
function settings(){return{bookTitle:val("bbBookTitle","My Activity Book"),subtitle:val("bbBookSubtitle",""),author:val("bbAuthor",""),welcome:val("bbWelcomeText",""),howto:val("bbHowToText",""),copyright:val("bbCopyrightText",""),trackerTitle:val("bbTrackerTitle","COMPLETE THE MISSION!"),trackerInstruction:val("bbTrackerInstruction",""),trackerCount:clamp(num("bbTrackerCount",50),1,200),trackerColumns:clamp(num("bbTrackerColumns",10),2,12),congrats:val("bbCongratsText",""),certificate:val("bbCertificateText",""),qr:val("bbQrText","")}}
function set(id,v){var n=$(id);if(n&&v!=null)n.value=String(v)}function apply(s){if(!s)return;set("bbBookTitle",s.bookTitle);set("bbBookSubtitle",s.subtitle);set("bbAuthor",s.author);set("bbWelcomeText",s.welcome);set("bbHowToText",s.howto);set("bbCopyrightText",s.copyright);set("bbTrackerTitle",s.trackerTitle);set("bbTrackerInstruction",s.trackerInstruction);set("bbTrackerCount",s.trackerCount);set("bbTrackerColumns",s.trackerColumns);set("bbCongratsText",s.congrats);set("bbCertificateText",s.certificate);set("bbQrText",s.qr)}
function wrap(ctx,text,maxWidth,fontSize){ctx.font=fontSize+"px Arial";var words=String(text||"").split(/\s+/),lines=[],line="";words.forEach(function(word){var test=line?line+" "+word:word;if(ctx.measureText(test).width>maxWidth&&line){lines.push(line);line=word}else line=test});if(line)lines.push(line);return lines}function drawStar(ctx,cx,cy,r){ctx.beginPath();for(var i=0;i<10;i++){var rr=i%2===0?r:r*.44,a=-Math.PI/2+i*Math.PI/5,x=cx+Math.cos(a)*rr,y=cy+Math.sin(a)*rr;if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.closePath();ctx.stroke()}
function pageTitle(type){return{welcome:"Welcome / Intro",belongs:"This Book Belongs To",howto:"How to Use",copyright:"Copyright",tracker:"Activity Mission Tracker",certificate:"Certificate",congratulations:"Congratulations",qr:"QR / Bonus"}[type]||"Strona pomocnicza"}
function draw(canvas,w,h,type,s){canvas.width=w;canvas.height=h;var ctx=canvas.getContext("2d"),scale=w/EW;ctx.save();ctx.fillStyle="#fff";ctx.fillRect(0,0,w,h);ctx.scale(scale,scale);ctx.fillStyle="#172033";ctx.strokeStyle="#172033";ctx.textAlign="center";ctx.textBaseline="middle";
if(type==="tracker"){ctx.font="bold 86px Arial";ctx.fillText(s.trackerTitle,EW/2,220,EW-360);ctx.font="40px Arial";ctx.fillText(s.trackerInstruction,EW/2,340,EW-420);var cols=s.trackerColumns,rows=Math.ceil(s.trackerCount/cols),left=250,right=2300,top=560,bottom=2850,cw=(right-left)/cols,ch=(bottom-top)/rows,r=Math.min(cw,ch)*.27;for(var i=0;i<s.trackerCount;i++){var c=i%cols,row=Math.floor(i/cols),x=left+c*cw+cw/2,y=top+row*ch+ch/2;ctx.lineWidth=5;drawStar(ctx,x,y,r);ctx.font="bold 24px Arial";ctx.fillText(String(i+1),x,y+r+34)}ctx.font="bold 36px Arial";ctx.fillText("Complete every activity and finish your mission!",EW/2,3100,EW-400)}
else if(type==="welcome"){ctx.font="bold 96px Arial";ctx.fillText(s.bookTitle,EW/2,520,EW-360);ctx.font="48px Arial";ctx.fillText(s.subtitle,EW/2,690,EW-420);ctx.font="42px Arial";wrap(ctx,s.welcome,1750,42).forEach(function(line,i){ctx.fillText(line,EW/2,1150+i*62)});if(s.author){ctx.font="bold 34px Arial";ctx.fillText(s.author,EW/2,2920)}}
else if(type==="belongs"){ctx.font="bold 88px Arial";ctx.fillText("THIS BOOK BELONGS TO",EW/2,650,EW-360);ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(470,1550);ctx.lineTo(2080,1550);ctx.stroke();ctx.font="34px Arial";ctx.fillText("Write your name here",EW/2,1640)}
else if(type==="howto"){ctx.font="bold 88px Arial";ctx.fillText("HOW TO USE THIS BOOK",EW/2,430,EW-360);ctx.font="42px Arial";wrap(ctx,s.howto,1750,42).forEach(function(line,i){ctx.fillText(line,EW/2,900+i*68)});ctx.font="bold 38px Arial";ctx.fillText("Have fun and do your best!",EW/2,2600)}
else if(type==="copyright"){ctx.font="bold 82px Arial";ctx.fillText("COPYRIGHT",EW/2,600);ctx.font="38px Arial";wrap(ctx,s.copyright,1750,38).forEach(function(line,i){ctx.fillText(line,EW/2,1150+i*62)});if(s.author){ctx.font="bold 34px Arial";ctx.fillText(s.author,EW/2,2600)}}
else if(type==="certificate"){ctx.lineWidth=10;ctx.strokeRect(180,180,EW-360,EH-360);ctx.font="bold 88px Arial";ctx.fillText("CERTIFICATE OF ACHIEVEMENT",EW/2,620,EW-420);ctx.font="38px Arial";ctx.fillText("Awarded to",EW/2,1030);ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(480,1450);ctx.lineTo(2070,1450);ctx.stroke();wrap(ctx,s.certificate,1700,38).forEach(function(line,i){ctx.fillText(line,EW/2,1850+i*60)});ctx.font="bold 42px Arial";ctx.fillText("Date: ____________",EW/2,2680)}
else if(type==="congratulations"){ctx.font="bold 104px Arial";ctx.fillText("CONGRATULATIONS!",EW/2,760,EW-360);ctx.font="44px Arial";wrap(ctx,s.congrats,1750,44).forEach(function(line,i){ctx.fillText(line,EW/2,1250+i*70)});ctx.font="bold 56px Arial";ctx.fillText("YOU DID IT!",EW/2,2550)}
else{ctx.font="bold 88px Arial";ctx.fillText("MORE FUN AWAITS!",EW/2,650,EW-360);ctx.strokeRect(925,1150,700,700);ctx.font="bold 34px Arial";ctx.fillText("QR CODE",EW/2,1500);ctx.font="40px Arial";wrap(ctx,s.qr,1600,40).forEach(function(line,i){ctx.fillText(line,EW/2,2200+i*62)})}ctx.restore()}
function preview(type){currentType=type;draw($("bbCanvas"),PW,PH,type,settings());$("bbPreviewTitle").textContent=pageTitle(type)}function blob(canvas){return new Promise(function(resolve,reject){canvas.toBlob(function(b){b?resolve(b):reject(new Error("Nie udało się utworzyć PNG."))},"image/png")})}
async function addPage(type){try{preview(type);var c=document.createElement("canvas"),s=settings();draw(c,EW,EH,type,s);var b=await blob(c),now=new Date().toISOString(),existing=editingPage&&editingPage.editorState&&editingPage.editorState.type===type?editingPage:null,page={id:existing?existing.id:id(),sourceModule:"book-builder",sourceLabel:"Book Builder",pageType:"book_builder_"+type,fileName:existing?existing.fileName:"fenix-"+type+"-page.png",title:pageTitle(type),width:EW,height:EH,mimeType:"image/png",createdAt:existing?existing.createdAt:now,updatedAt:now,blob:b,order:existing?existing.order:Date.now(),includeInBook:existing?existing.includeInBook!==false:true,editorState:{type:type,settings:s}};await window.FenixBasket.putPage(page);editingPage=page;$("bbStatus").textContent=existing?"Zapisano zmiany strony w Koszyku Feniksa.":"Dodano stronę „"+pageTitle(type)+"” do Koszyka Feniksa.";refreshCount()}catch(e){console.error(e);$("bbStatus").textContent="Błąd: "+e.message}}
async function loadEditing(){var pageId=new URLSearchParams(location.search).get("basketPageId");if(!pageId)return;try{var page=await window.FenixBasket.getPage(pageId);if(!page||page.sourceModule!=="book-builder"||!page.editorState)throw new Error("Brak danych edycji strony.");editingPage=page;apply(page.editorState.settings);preview(page.editorState.type);$("bbStatus").textContent="Tryb edycji: "+page.title+". Kliknij właściwy przycisk dodawania, aby zapisać zmiany."}catch(e){$("bbStatus").textContent="Nie udało się otworzyć strony do edycji: "+e.message}}
async function refreshCount(){try{var pages=await window.FenixBasket.getAllPages();$("bbBasketCount").textContent="Koszyk: "+pages.length+" stron"}catch(_){}}
async function init(){var grid=$("bbModuleGrid");modules.forEach(function(m){var a=document.createElement("a");a.className="bb-module";a.href=m[2];a.innerHTML="<i>"+m[0]+"</i><span><b>"+m[1]+"</b><small>Otwórz moduł</small></span>";grid.appendChild(a)});document.querySelectorAll("[data-add-page]").forEach(function(btn){btn.addEventListener("mouseenter",function(){preview(btn.dataset.addPage)});btn.addEventListener("focus",function(){preview(btn.dataset.addPage)});btn.addEventListener("click",function(){addPage(btn.dataset.addPage)})});document.querySelectorAll("input,textarea").forEach(function(n){n.addEventListener("input",function(){preview(currentType)})});preview("welcome");await loadEditing();refreshCount()}
document.addEventListener("DOMContentLoaded",init);
})();